"""DEMO-LOCAL MUMPS executor. A stopgap, not the verifier.

WHAT THIS IS NOT: this is not `rosetta.core`. Stream A owns real execution --
TP-framed isolation, global-state capture, a long-lived supervised worker,
void/restart handling. None of that is here.

WHAT THIS IS: the smallest thing that runs a real VistA routine and a modified
copy of it against the live VEHU container, so the demo can show a *real*
divergence today instead of a fabricated one. It compares stdout and error
only -- NO GLOBAL DIFFING. Both demo tasks are read-only routines, so that is
sound for them and unsound in general. See `rosetta.demo.verifier` for the seam
where the real verifier attaches.

SAFETY: never writes to /home/vehu. Modified routines go to a per-run temp
directory inside the container which is prepended to $gtmroutines, shadowing
the real routine for this process only. VistA's routine store and globals are
untouched. Nothing here SETs a global.

Costs one `docker exec` per case (~0.5s), which is exactly the per-invocation
cost docs/PROJECT.md #6 says to avoid in the benchmark hot loop. Fine for a
handful of demo cases; not fine for datagen.
"""

from __future__ import annotations

import shlex
import subprocess
import time
import uuid
from dataclasses import dataclass

from rosetta.core.interface import ExecResult, ExecSpec

OUT_MARK = "<<<ROSETTA-OUT>>>"
ERR_MARK = "<<<ROSETTA-ERR>>>"
END_MARK = "<<<ROSETTA-END>>>"

DRIVER_NAME = "ZRDEMODRV"


class VistaExecError(RuntimeError):
    """The container, docker, or the M compiler failed. Not a test failure."""


@dataclass(frozen=True)
class VistaExecConfig:
    """Where and how to run. `container` must already be running."""

    container: str = "vehu"
    gtm_dist: str = "/home/vehu/lib/gtm"
    root: str = "/tmp/rosetta-demo"
    docker: str = "docker"
    timeout_s: float = 60.0


def _run(cmd: list[str], *, stdin: str | None = None, timeout: float) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            cmd,
            input=stdin,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError as exc:
        raise VistaExecError(f"{cmd[0]!r} not found on PATH") from exc
    except subprocess.TimeoutExpired as exc:
        raise VistaExecError(f"timed out after {timeout}s: {' '.join(cmd[:4])}...") from exc


def container_available(cfg: VistaExecConfig | None = None) -> bool:
    """True if the container is running. The canned demo path never calls this."""
    cfg = cfg or VistaExecConfig()
    try:
        proc = _run(
            [cfg.docker, "inspect", "-f", "{{.State.Running}}", cfg.container],
            timeout=15.0,
        )
    except VistaExecError:
        return False
    return proc.returncode == 0 and proc.stdout.strip() == "true"


def _write_file(cfg: VistaExecConfig, path: str, content: str) -> None:
    proc = _run(
        [cfg.docker, "exec", "-i", cfg.container, "sh", "-c", f"cat > {shlex.quote(path)}"],
        stdin=content,
        timeout=cfg.timeout_s,
    )
    if proc.returncode != 0:
        raise VistaExecError(f"could not write {path}: {proc.stderr.strip()}")


def _build_driver(spec: ExecSpec) -> str:
    """Generate the M driver that sets up locals, makes the call, marks output.

    args and locals_in values are MUMPS *source expressions*, not Python values:
    a string literal must arrive already quoted, e.g. args=['4', '"NOK"'].
    That keeps the contract honest -- there is no hidden coercion layer that
    could make the demo disagree with what a real caller would see.
    """
    lines = [f"{DRIVER_NAME} ;generated by rosetta.demo.vista_exec -- do not edit", "RUN ;"]
    lines.append(f' N %ROSR S $ETRAP="D ERR^{DRIVER_NAME}"')
    for name, value in spec.locals_in.items():
        lines.append(f" S {name}={value}")
    if spec.globals_in:
        raise VistaExecError(
            "globals_in is not supported by the demo executor: it would require "
            "writing to the live database. Use rosetta.core when it lands."
        )
    call = f"{spec.entry}^{spec.routine}" if spec.entry else spec.routine
    if spec.entry:
        arglist = ",".join(spec.args)
        lines.append(f" S %ROSR=$${call}({arglist})")
    else:
        lines.append(f" D {call} S %ROSR=\"\"")
    lines.append(f' W "{OUT_MARK}",%ROSR,"{END_MARK}",!')
    lines.append(" Q")
    lines.append("ERR ;")
    lines.append(f' W "{ERR_MARK}",$ZSTATUS,"{END_MARK}",!')
    lines.append(' S $ECODE=""')
    lines.append(" H")
    return "\n".join(lines) + "\n"


def _parse(raw: str) -> tuple[str, str | None]:
    """Return (stdout_value, error). Marker-delimited so incidental VistA
    chatter before the call cannot be mistaken for the result."""
    for mark, is_error in ((OUT_MARK, False), (ERR_MARK, True)):
        start = raw.find(mark)
        if start == -1:
            continue
        start += len(mark)
        end = raw.find(END_MARK, start)
        if end == -1:
            raise VistaExecError(f"unterminated {mark} in output: {raw[:400]!r}")
        payload = raw[start:end]
        return ("", payload) if is_error else (payload, None)
    return "", f"NOMARKER: {raw.strip()[:400]}"


def execute(
    spec: ExecSpec,
    sources: dict[str, str],
    cfg: VistaExecConfig | None = None,
) -> ExecResult:
    """Run one spec with `sources` shadowing the real routines.

    `sources` maps routine name -> source. Anything not listed resolves to the
    container's real routine, which is what makes a one-routine change testable
    against the rest of live VistA.
    """
    cfg = cfg or VistaExecConfig()
    if not sources:
        raise VistaExecError("sources must contain at least the routine under test")

    run_id = uuid.uuid4().hex[:12]
    base = f"{cfg.root}/{run_id}"
    rdir, odir = f"{base}/r", f"{base}/o"

    mk = _run(
        [cfg.docker, "exec", cfg.container, "mkdir", "-p", rdir, odir],
        timeout=cfg.timeout_s,
    )
    if mk.returncode != 0:
        raise VistaExecError(f"mkdir failed in {cfg.container}: {mk.stderr.strip()}")

    try:
        for name, src in sources.items():
            if not src.endswith("\n"):
                src += "\n"
            _write_file(cfg, f"{rdir}/{name}.m", src)
        _write_file(cfg, f"{rdir}/{DRIVER_NAME}.m", _build_driver(spec))

        shell = (
            f'export gtmroutines="{odir}*({rdir}) $gtmroutines"; '
            f"cd /tmp; exec {cfg.gtm_dist}/mumps -run RUN^{DRIVER_NAME}"
        )
        started = time.monotonic()
        proc = _run(
            [cfg.docker, "exec", cfg.container, "bash", "-lc", shell],
            timeout=max(cfg.timeout_s, spec.timeout_s + 30.0),
        )
        duration_ms = int((time.monotonic() - started) * 1000)

        stdout, error = _parse(proc.stdout + proc.stderr)
        return ExecResult(
            stdout=stdout,
            error=error,
            globals_out={},  # not captured -- see module docstring
            duration_ms=duration_ms,
            restarts=0,
            void=False,
        )
    finally:
        _run([cfg.docker, "exec", cfg.container, "rm", "-rf", base], timeout=30.0)
