PAYMENT ; Payment application service; amounts are integer cents
POST(ID,ACCOUNT,AMOUNT) ; returns receipt; one invocation is one payment
 N RECORD,BALANCE
 I ID="" Q "ERROR:ID"
 I ACCOUNT="" Q "ERROR:ACCOUNT"
 I AMOUNT'?1.N Q "ERROR:AMOUNT"
 I AMOUNT=0 Q "ERROR:AMOUNT"
 S BALANCE=$$BALANCE^PAYSTORE(ACCOUNT)+AMOUNT
 D SAVE^PAYSTORE(ACCOUNT,BALANCE)
 S RECORD=ACCOUNT_"^"_AMOUNT_"^"_BALANCE
 D RECEIPT^PAYSTORE(ID,RECORD)
 Q "OK^"_BALANCE
